### ISSUE TITLE
[CK][Support] App slow on Home button click.

### ISSUE THREAD

**Issue by garimadosar5** [avniproject/calcutta-kids#33]
ticket - https://avni.freshdesk.com/a/tickets/589
https://avni.freshdesk.com/a/tickets/595

**Comment by vindeolal** [comment]
@garimadosar5 Changes done
- For CK home click takes around 30 or more seconds (this was due to a lot of individuals returned by All query). Fixed it (now it takes around 4 sec for CK in tablet). 
- Added activityIndicator when applying any filters, searching a subject and when loading list of the subjects (cards in myDashboard).
