### ISSUE TITLE
[CK] few reports are not working

### ISSUE THREAD

**Issue by garimadosar5** [avniproject/calcutta-kids#37]
https://reporting.avniproject.org/question/185

https://reporting.avniproject.org/question/324

**Comment by hithacker** [comment]
Analysis notes:
- first issue- not working because we removed is_admin column from table and report was using it. Fixed it by removing the check. It was not really necessary.
- second issue - not working because “Enc.Date of delivery” field has become textfield now but we are comparing it with date variable. Might be because of metabase upgrade becoming stricter. This was a old report and earlier our view generation service did not add casting on date fields automatically. Nowadays we do that so should not be an issue in future. There is another issue though with this report that when this query runs for long time it throws an error “user query might have needed to see row versions that must be removed.”. There is this https://aws.amazon.com/blogs/database/best-practices-for-amazon-rds-postgresql-replication/ which suggest that we can set hot_standby_feedback to true on read replica but it’s risky. Might be better to let users retry unless we see more such issues.
