### ISSUE TITLE
Dashboard report 5th - 9th

### ISSUE THREAD

**Issue by salilsamanvay** [avniproject/calcutta-kids#63]
## Context: 
This dashboard part is to monitor the vaccination and babies delivered either at home or institutional

for logic requirement document confirmed by client refer below link: https://docs.google.com/spreadsheets/d/1AzSqMT0ksZAes29qxpWAINOIDE3mrFv3/edit?usp=drive_link&ouid=111559638012526864678&rtpof=true&sd=true

for dashboard layout please refer: https://drive.google.com/file/d/11byBuuykwd5EWllVRb9cilKrpeV4FV-z/view?usp=drive_link

- [ ] Child program: Percentage of child which are fully vaccinated  **area wise** (Bar graph)
- [ ] Child program: Percentage of child which are fully vaccinated (Pie chart)
- [ ] Child program: Percentage of child which are fully vaccinated **month wise** (Bar graph)
- [x] Maternal Program: Babies born (Numeric count)
- [x] Maternal Program: Percentage of medical Facility birth (percentage in numeric form)

above report are to be added to Dashboard which is created for CK: 
https://reporting.avniproject.org/dashboard/222-dashboard-reports

**Comment by nupoorkhandelwal** [comment]
Here is the base query to get the each vaccination's due date and completion date --

**Comment by nupoorkhandelwal** [comment]
Here is the base query to get the each vaccination's due date and completion date --

**Comment by vedfordev** [comment]
@salilsamanvay 
Following Details are not cleared 
1. babies born logic is not clear.
2. program exit should be consider or not that not mentioned.
3. reference report was not given for first report.

**Comment by vedfordev** [comment]
@nupoorkhandelwal  Please find issue below : 

1. Child program: Percentage of child which are fully vaccinated area wise (Bar graph)

issue : tried with both way with aggregating  query and with using summaries. for aggregating we are not using date that's why filter is not accessible for that.
for summaries I find articles that we can't provide filter at two level of summaries.[Link1](https://discourse.metabase.com/t/dashboard-filter-on-query-with-two-summary-steps/11395/11) [Link2](https://discourse.metabase.com/t/cant-filter-dashboard-with-double-aggregation/12569)

2. Child program: Percentage of child which are fully vaccinated (Pie chart)

issue : same as above

3. Child program: Percentage of child which are fully vaccinated month wise (Bar graph)

issue : first we have to fix month and year filter issue then we can proceed with that and may be have same filter issue

**Comment by vedfordev** [comment]
@salilsamanvay moving card to on hold with following issue.
@sachsk / @nupoorkhandelwal please check above issue.

**Comment by salilsamanvay** [comment]
Moving this card to ready lane as for year filter we can only provide date range options, whoever picks this card can check once if range filter is applied to all the indicators and report is completed or not as per requirement, before giving it to QA.

**Comment by vedfordev** [comment]
@vaijayanthisundaram check above tech notes

**Comment by AnjaliBhagabati** [comment]
@sachsk can you check on this. @vedfordev is having issue on applying the filter

**Comment by AnjaliBhagabati** [comment]
@sachsk can you check on this. @vedfordev is having issue on applying the filter

**Comment by vedfordev** [comment]
@sachsk created linelist [Report](https://reporting.avniproject.org/question/3022-child-vaccination-by-area-linelist). Please check.
